# Copyright (C) 2024 IOTech Ltd
# SPDX-License-Identifier: Apache-2.0

"""
Constants for the App Functions SDK.

This module defines constants that are used throughout the App Functions SDK.
"""

DEFAULT_PROFILE_SUFFIX_PLACEHOLDER = "<profile>"

DEFAULT_PIPELINE_ID = "default-pipeline"

TRIGGER_TYPE_MESSAGEBUS = "EDGEX-MESSAGEBUS"
TRIGGER_TYPE_MQTT = "EXTERNAL-MQTT"
TRIGGER_TYPE_HTTP = "HTTP"

DEFAULT_TRIGGER_TYPE = TRIGGER_TYPE_MESSAGEBUS

TOPIC_WILDCARD = "#"
TOPIC_SINGLE_LEVEL_WILDCARD = "+"
TOPIC_LEVEL_SEPERATOR = "/"
TARGET_TYPE_RAW = "raw"
TARGET_TYPE_EVENT = "event"
TARGET_TYPE_METRIC = "metric"
TARGET_TYPE_EMPTY = ""

KEY_DEVICE_NAME = "devicename"
KEY_PROFILE_NAME = "profilename"
KEY_SOURCE_NAME = "sourcename"
KEY_RECEIVEDTOPIC = "receivedtopic"
KEY_PIPELINEID = "pipelineid"

SPILT_COMMA = ","

SECRET_USERNAME_KEY = "username"
SECRET_PASSWORD_KEY = "password"
SECRET_CLIENT_KEY = "clientkey"
SECRET_CLIENT_CERT = "clientcert"
SECRET_CA_CERT = "cacert"

DB_SQLITE = "sqlite"

ENV_KEY_SECURITY_SECRET_STORE = "EDGEX_SECURITY_SECRET_STORE"
ENV_KEY_DISABLE_JWT_VALIDATION = "EDGEX_DISABLE_JWT_VALIDATION"
ENV_KEY_CONFIG_PROVIDER_URL = "EDGEX_CONFIG_PROVIDER"
ENV_KEY_COMMON_CONFIG = "EDGEX_COMMON_CONFIG"
ENV_KEY_USE_REGISTRY = "EDGEX_USE_REGISTRY"
ENV_KEY_STARTUP_DURATION = "EDGEX_STARTUP_DURATION"
ENV_KEY_STARTUP_INTERVAL = "EDGEX_STARTUP_INTERVAL"
ENV_KEY_CONFIG_DIR = "EDGEX_CONFIG_DIR"
ENV_KEY_PROFILE = "EDGEX_PROFILE"
ENV_KEY_CONFIG_FILE = "EDGEX_CONFIG_FILE"
ENV_KEY_FILE_URI_TIMEOUT = "EDGEX_FILE_URI_TIMEOUT"
ENV_KEY_REMOTE_SERVICE_HOSTS = "EDGEX_REMOTE_SERVICE_HOSTS"
ENV_EDGEX_MSG_BASE64_PAYLOAD = "EDGEX_MSG_BASE64_PAYLOAD"
